"""
Django settings for netday project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "paypalrestsdk",
    "paypal.standard.ipn",
    "netday",
    "rest_framework",
    "corsheaders",

]

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")

PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_CLIENT_SECRET = os.getenv("PAYPAL_CLIENT_SECRET")
PAYPAL_MODE = os.getenv("PAYPAL_MODE")
PAYPAL_RECEIVER_EMAIL = os.getenv("PAYPAL_RECEIVER_EMAIL")
PAYPAL_TEST = True

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",

]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]
CORS_ALLOW_HEADERS = [
    'access-control-allow-origin',
    'content-type',
    'x-custom-header',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
]

ROOT_URLCONF = "netday.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "netday.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

SITE_ID = 1

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FRONTEND_URL = os.getenv("FRONTEND_URL")
PAYMENT_CONFIRMATION_URL = os.getenv("PAYMENT_CONFIRMATION_URL")

EMAIL_MESSAGE = """
Dear participant,

It is our pleasure to have you as a participant in the NetDay event!
Here is information about the first round of the Olympiad.

The date of the first (preliminary) tour is on the 4th of November
Time: start login time: 18:00 - end login time: 19:00 UTC+06:00 (+6)
(you can start anytime during 18:00-19:00, e.g if you start the exam at 18:10, the exam finishes at 19:10 for you)
Duration: 1 hour
Format: Online, multiple-choice, True and False, Fill-in questions
 
The day of the exam:

You will receive a link to the exam on the day of the preliminary tour. In case of the successful completion of the exam, a limited amount of students will be forwarded to the next tour, which will be offline at the SDU campus. 
Before starting the exam make sure of 3 rules:
·        Good internet connection
·        Quiet place and being alone during preliminary exam
·        No gadgets and headphones (earphones, AirPods and etc)
 
For instructions and rules of the first round of NetDay, see the link https://docs.google.com/document/d/1dMC2RCKnpZ4_uhNHabZshdIgaSIN9Ahaac7zJ8qeIh0/edit?usp=sharing 

Wait for updates and news from our official telegram: https://t.me/sdunetday 
Contact us for any questions and concerns at netday@sdu.edu.kz or telegram

******
Құрметті Олимпиада қатысушысы,
 
Сізді NetDay олимпиадасының қатысушысы ретінде көргенімізге қуаныштымыз.
Осы хабарламада олимпиаданың бірінші туры туралы ақпарат берілген
 
Бірінші тур 4 қарашада болады
Жүйеге кірудің басталу уақыты: 18:00 - кірудің аяқталу уақыты: 19:00 UTC+06:00 (+6) 
(сіз 18:00-ден 19:00-ге дейін кез келген уақытта бастай аласыз, мысалы, емтиханды 18:10-да бастасаңыз, емтихан сіз үшін 19:10-да аяқталады)
Емтихан ұзақтығы: 1 сағат
Форматы: онлайн

Емтихан алдында:
Сіз емтиханға сілтемені алдын ала Бірінші тур өтетін күні аласыз. Емтиханды сәтті тапсырған жағдайда үздік студенттер СДУ кампусында офлайн режимде өтетін келесі турға жіберіледі.
 
Емтиханды бастамас бұрын мына 3 ережені орындағаныңызға көз жеткізіңіз:
·        Жақсы интернет байланыстың болуы
·        Емтихан кезінде тыныш әрі жалғыз болу
·        Гаджеттер немесе құлаққаптардың (airPods, т.б.) болмауы
 
NetDay бірінші раундының нұсқаулары мен ережелері осы сілтемеден қараңыз https://docs.google.com/document/d/1dMC2RCKnpZ4_uhNHabZshdIgaSIN9Ahaac7zJ8qeIh0/edit?usp=sharing 

Жаңартулар мен жаңалықтар біздің ресми телеграм каналда жарияланады: https://t.me/sdunetday 
Сұрақтарыңызды электронды поштаға (netday@sdu.edu.kz) немесе телеграм арқылы қойсаңыз болады
 

******
Уважаемый участник,
 
Мы рады видеть вас в качестве участника Олимпиады NetDay.
Перед Вами информация о первом туре олимпиады
 
Дата первого (предварительного) тура - 4 ноября.
Время начала входа: 18:00 - время окончания входа: 19:00 UTC+06:00 (+6) 
(вы можете начать экзамен с 18:00 до 19:00, например, если вы начнете экзамен в 18:10, экзамен заканчивается для вас в 19:10)
Продолжительность экзамена: 1 час
Формат: онлайн 
 
В день олимпиады:
Ссылку на экзамен Вы получите в день предварительного тура. В случае успешной сдачи ограниченное количество студентов будут направлены на следующий тур, который будет проходить в формате оффлайн на кампусе СДУ.
 
Перед началом экзамена убедитесь в соблюдении 3х правил:
·   Хорошее интернет соединение
·   Тихое место во время предварительного экзамена
·    Никаких гаджетов и наушников (наушники, airPods и т.п.)
 
Инструкции и правила первого тура NetDay смотрите по ссылке https://docs.google.com/document/d/1dMC2RCKnpZ4_uhNHabZshdIgaSIN9Ahaac7zJ8qeIh0/edit?usp=sharing 

Новости и обновления можете отследить у нас в официальном телеграм канале: https://t.me/sdunetday
При возникновении вопросов пишите на netday@sdu.edu.kz или в чат телеграм канала
"""
