# Generated by Django 4.2.6 on 2023-10-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=25)),
                ("country", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=200)),
                ("major", models.CharField(max_length=100)),
                ("course", models.IntegerField()),
                ("isPay", models.BooleanField(default=False)),
                ("payment_id", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "netday_registration",
            },
        ),
    ]
